# Generated by Django 2.1.3 on 2018-12-15 18:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Cuestionario')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Creado')),
                ('actualizado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Ultima Actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15, unique=True, verbose_name='Día')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Creado')),
                ('actualizado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Ultima Actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre Grupo')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Creado')),
                ('actualizado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Ultima Actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Creado')),
                ('actualizado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Ultima Actualizacion')),
                ('dias', models.ManyToManyField(to='webapp.Dia', verbose_name='Días')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_espanol', models.TextField(verbose_name='Pregunta Espanol')),
                ('pregunta_ingles', models.TextField(verbose_name='Pregunta Ingés')),
                ('intitucional', models.BooleanField(default=False, verbose_name='Pregunta Institucional')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Creado')),
                ('actualizado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Ultima Actualizacion')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preguntas', to='webapp.Cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre Profesor')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Creado')),
                ('actualizado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Ultima Actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Creado')),
                ('actualizado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Ultima Actualizacion')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Cuestionario', verbose_name='Cuestionario')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Grupo', verbose_name='Grupo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Profesor', verbose_name='Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Creado')),
                ('actualizado_en', models.DateField(default=datetime.date.today, verbose_name='Fecha Ultima Actualizacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Pregunta')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='respuestas', to='webapp.Registro')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Horario', verbose_name='Horario'),
        ),
    ]
